// This file is auto-generated by keycloakify. Do not edit it manually.
// Hash: 1cc768df6b95ba2151c9232fb211d9ed9cfe78d6c5b16e4ecdbb2b19bae1f591

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

export type ThemeName = 'keycloakify-starter-svelte';

export const themeNames: ThemeName[] = ['keycloakify-starter-svelte'];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext = import('./login/KcContext').KcContext | import('./account/KcContext').KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}
