<script lang="ts">
// This file is auto-generated by keycloakify. Do not edit it manually.
// Hash: 9aa1d1843f1db442cc1d576d9e84327769545b0957588aa5f9294e185ae56e92

  import type { Component } from 'svelte';
  import type { KcContext } from './kc.gen';

  const props: { kcContext: KcContext; Fallback?: Component } = $props();

  const KcLoginPage = import('./login/KcPage.svelte');
  const { kcContext } = props;
</script>

{#if kcContext.themeType === 'login'}
  {#await KcLoginPage}
    {#if props.Fallback}
      <props.Fallback></props.Fallback>
    {/if}
  {:then { default: KcPage }}
    <KcPage {kcContext} />
  {/await}
{:else}
  null
{/if}