// This file is auto-generated by keycloakify. Do not edit it manually.
// Hash: 9aa1d1843f1db442cc1d576d9e84327769545b0957588aa5f9294e185ae56e92

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

export type ThemeName = 'keycloakify-starter-svelte';

export const themeNames: ThemeName[] = ['keycloakify-starter-svelte'];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext = import('./login/KcContext.gen').KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}
// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from '@storybook/svelte-vite';
