<script lang="ts">
  // This file is auto-generated by keycloakify. Do not edit it manually.
  // Hash: ad84315ebc9a234f9a2e1a20d99fc36eb3d69a6edb4a26cbf740984cd333c9cd

  import type { Component } from 'svelte';
  import type { KcContext } from './kc.gen';

  const { kcContext, Fallback }: { kcContext: KcContext; Fallback?: Component } = $props();

  const KcLoginPage = import('./login/KcPage.svelte');
  const KcAccountPage = import('./account/KcPage.svelte');
</script>

{#if kcContext.themeType === 'login'}
  {#await KcLoginPage}
    {#if Fallback}
      <Fallback></Fallback>
    {/if}
  {:then { default: KcPage }}
    <KcPage {kcContext} />
  {/await}
{:else if kcContext.themeType === 'account'}
  {#await KcAccountPage}
    {#if Fallback}
      <Fallback></Fallback>
    {/if}
  {:then { default: KcPage }}
    <KcPage {kcContext} />
  {/await}
{/if}
