// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 41b0a7c403a577671a640e1e49e3913c71cd56331a7aefcd566f5419b621f023

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

export type ThemeName = 'keycloakify-starter-svelte';

export const themeNames: ThemeName[] = ['keycloakify-starter-svelte'];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext = import('./login/KcContext').KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}
